### PR TITLE
Removed cnv argocd deployment manifests.

### PR DESCRIPTION
**Pull request by HumairAK**
CNV argocd instance has been decommissioned, the manifests aren't needed any more. 

Post merge steps: 
- remove the cnv resources from cnv cluster

### CODE REVIEW

**Review by tumido — COMMENTED** [review]
nice cleanup

/lgtm

**Comment by anishasthana** [comment]
kustomize build worked. /lgtm

**Review by 4n4nd — COMMENTED** [review]
/lgtm

**Pull request merged**
