### PR TITLE
Add instructions on increasing CRC disk size.

### PR DESCRIPTION
**Pull request by martinpovolny**
* how to add more memory to your CRC.

### CODE REVIEW

**Review by tumido — APPROVED** [review]
Just a suggestion. What about adding a playbook as an alternative to manual steps? :wink: 

Otherwise LGTM :+1:

**Comment by martinpovolny** [comment]
> Just a suggestion. What about adding a playbook as an alternative to manual steps? wink

@tumido : Let me do it in a follow up PR. Ok?

**Comment by tumido** [comment]
sounds good :+1:

**Review by tumido — APPROVED** [review]

**Pull request merged**
