### PR TITLE
Update ArgoCD to 1.8.3, helm-secrets, ksops

### LINKED ISSUE #84: Helm-Secrets deprecated, switch to new repo
As per this repo [here](https://github.com/zendesk/helm-secrets) 

> Please note, this project is no longer being maintained. There is an active fork jkroepke/helm-secrets and we will also contribute our future changes to it.

We should switch to the one [here](https://github.com/jkroepke/helm-secrets).

### PR DESCRIPTION
**Pull request by HumairAK**
As per instructions in this [doc](https://github.com/operate-first/continuous-deployment/blob/master/docs/admin/update_argocd.md)

Fixes #84 #90 #95 
Also slightly adds more info for update docs.

This should solve our build failures as well during ci for this repo in particular.

### CODE REVIEW

**Comment by anishasthana** [comment]
Might be too late for this, but any chance we could split this into three separate commits (ArgoCD, Helm Secrets, KSOPS)? I'm not a fan of one commit for three different sets of changes

**Review by anishasthana — COMMENTED** [review]
As a whole the changes look good to me. Should downstream IDH also aim to update their manifests?

**Review by tumido — APPROVED** [review]
I haven't tested it out. Other than that, LGTM.

**Comment by HumairAK** [comment]
@anishasthana  I think in this case it's fine,  since I'm upping the tooling version to 1.8.3-1 as part of all 3 tools being updated. for each commit I'd need to do 1.8.3-1, 1.8.3-2, 1.8.3-3 each commit, and that would be overkill.

**Review by anishasthana — APPROVED** [review]
:ship:

**Pull request merged**
