### PR TITLE
Update dev cluster to use in-cluster name & use all namespaces in the spec

### PR DESCRIPTION
**Pull request by HumairAK**
The name change here is to be more consistent with the argocd applications in our app-repo. See [here](https://github.com/operate-first/argocd-apps/blob/main/base/operate-first/dashboard.yaml#L8) for an example. This name is the standard cluster name we've set in that repo in the base, so the deployment here should reflect that. I've kept the name of the secret the same, so that we don't have to change the various scripts/docs we've added that make use of it.

I've also removed the namespaces (this giving the c luster spec access to all namespaces) since we're giving the dev cluster cluster admin anyway, limiting namespaces is not necessary.

### CODE REVIEW

**Review by tumido — APPROVED** [review]
LGTM :+1:

**Comment by HumairAK** [comment]
/unhold 

Ignore build test failures, it's due to docker ratelimiting

**Review by hemajv — APPROVED** [review]
lgtm :+1:

**Pull request merged**
