### PR TITLE
feat: Create workshops app project

### PR DESCRIPTION
**Pull request by tumido**
Part of: https://github.com/operate-first/support/issues/77
Depends on: #101

### CODE REVIEW

**Comment by HumairAK** [comment]
@tumido  can you also add the workshops group to the dex config as described [here](https://github.com/operate-first/support/blob/main/docs/onboarding_to_argocd.md#enable-openshift-auth-to-argocd-console)

**Comment by tumido** [comment]
@HumairAK done! :slightly_smiling_face:  please re-review

**Pull request merged**
