### PR TITLE
Update ArgoCD to 1.8.1

### LINKED ISSUE #82: Update to argocd 1.8.1

### PR DESCRIPTION
**Pull request by HumairAK**
Fixes #82

Notes:
 - added docs for the update process.
 - updated ci config to push tag releases to quay.io/operate-first/argocd
 - removed redis patch, as the securitycontext nonroot issue has been resolved in the newer argocd version 
 - removed imagestreams, instead of using local registry reference, we're just now directly referencing from quay

### CODE REVIEW

**Review by tumido — APPROVED** [review]
LGTM :+1: 

I like the docs, thank you for that! :slightly_smiling_face:

**Review by 4n4nd — APPROVED** [review]
looks good :ship:

**Comment by tumido** [comment]
@HumairAK FYI the build has failed:
https://tekton-dashboard-openshift-pipelines.apps.ocp4.prod.psi.redhat.com/#/namespaces/aicoe-infra-prod/pipelineruns/tag-release-b7ggb

```
+ buildah bud --storage-driver=overlay --tls-verify=false --layers -f /gen-source/Containerfile -t continuous-deployment-v1.8.1-1 .
STEP 1: FROM viaductoss/ksops:v2.3.2 AS ksops-builder
Completed short name "viaductoss/ksops" with unqualified-search registries (origin: /etc/containers/registries.conf)
STEP 2: FROM argoproj/argocd:v1.8.1
Completed short name "argoproj/argocd" with unqualified-search registries (origin: /etc/containers/registries.conf)
error creating build container: 4 errors occurred while pulling:
 * Error initializing source docker://registry.fedoraproject.org/viaductoss/ksops:v2.3.2: Error reading manifest v2.3.2 in registry.fedoraproject.org/viaductoss/ksops: manifest unknown: manifest unknown
 * Error initializing source docker://registry.access.redhat.com/viaductoss/ksops:v2.3.2: Error reading manifest v2.3.2 in registry.access.redhat.com/viaductoss/ksops: name unknown: Repo not found
 * Error initializing source docker://registry.centos.org/viaductoss/ksops:v2.3.2: Error reading manifest v2.3.2 in registry.centos.org/viaductoss/ksops: manifest unknown: manifest unknown
 * Error initializing source docker://viaductoss/ksops:v2.3.2: Error reading manifest v2.3.2 in docker.io/viaductoss/ksops: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```

**Comment by HumairAK** [comment]
Thanks @tumido I manually pushed it, not sure how we can avoid those kind of issues, as the image has to come from docker before we push to quay .

**Comment by tumido** [comment]
Not sure, we can clone (copy over) the ksops image from dockerhub to quay first and then reference our quay image copy the same way we do it for redis, and then release via CI. WDYT?

**Comment by HumairAK** [comment]
That's the only solution I could think of as well. But then we're still left with the argocd image which comes from docker, I'm guessing had the ksops image not been there, it would have failed on the argocd image instead since that's imported later in the build. We could then also maintain an argocd clone as well. But that's 2 manual steps, vs me just manually pushing the final image which is 1 step.

**Comment by HumairAK** [comment]
I'm comfortable with waiting for a solution upstream and sticking to manual pushes when tag release fails (we don't tag release _that_ often). I can make an issue upstream for ksops. ArgoCD is already trying to come up with their own solutions (see [here](https://github.com/argoproj/argo-cd/issues/4917)) wdyt?

**Pull request merged**
