### PR TITLE
Add routes for argocd metrics

### PR DESCRIPTION
**Pull request by 4n4nd**
Add routes for argocd-dex-server argocd-repo-server

### CODE REVIEW

**Review by tumido — COMMENTED** [review]
/lgtm

**Comment by HumairAK** [comment]
@4n4nd can you add these to the moc-infra overlay instead? and have one file for each route? You would need to create a new dir for routes in `manifests/overlays/moc-infra/routes`. 

Base is used by idh folks. I don't expect exposing these metrics path to expose anything confidential, I'd rather err on the side of caution and just add them for the moc-infra instance. If we find it's a common use-case later, we can move it to overlay later. Wdyt?

**Review by anishasthana — COMMENTED** [review]
/lgtm

**Comment by anishasthana** [comment]
On the other hand, we could look at the metrics and if nothing looks shady we can just keep it in base. I always like more metrics

**Review by anishasthana — APPROVED** [review]
/lgtm

I took a look at the metrics and nothing popped out as "bad" to me

**Comment by HumairAK** [comment]
If the idh rep says it's good then I can't complain :man_shrugging:

**Comment by HumairAK** [comment]
changes applied

**Pull request merged**
