### PR TITLE
Add the kustomize-hash-annotator kustomize plugin

### PR DESCRIPTION
**Pull request by accorvin**
This adds the kustomize-hash-annotator [1] kustomize plugin to the
ArgoCD image. This plugin allows for dynamically annotating an object
with the hash of the contents of a configmap or secret, allowing for,
among other things, automatic rollouts of deployments based on updates
to configmaps and secrets.

[1]: https://github.com/pcjun97/kustomize-hash-annotator

### CODE REVIEW

**Comment by accorvin** [comment]
@HumairAK I think maybe you're the maintainer of this. What do you think of this addition?

**Comment by Gregory-Pereira** [comment]
It seems that the pre-commit pod cannot connect to GitHub (connection timeout) to clone down the pre-commit repo. I Will look into this.
/retest

**Comment by Gregory-Pereira** [comment]
checking to see if the build-check also clones a git repo or uses networking in any way, to determine if this issue also affects other checks.
/retest

**Comment by HumairAK** [comment]
I think this will result in the same issue as: https://github.com/operate-first/toolbox/pull/80#issuecomment-1181777707 

I.e. the entry for `kind:` field will be `hashannotator` and not `HashAnnotator`, the latter is what I think you are currently using in your manifests in idh.

**Comment by accorvin** [comment]
@HumairAK do you have a take on which case is "correct"?

**Comment by HumairAK** [comment]
@accorvin I think the creator intended for `HashAnnotator` to be the correct one, since that's what  their make file creates, and is shown in the examples.

**Comment by accorvin** [comment]
@HumairAK as in the toolbox repo, this should be fixed now.

**Pull request merged**
